set role service_role;
select test.assert_equals('paid_failure_waits_for_accepted_organizer',(select count(*) from private.reward_fulfillments f join public.consequences co on co.id=f.consequence_id where co.challenge_id='a2000000-0000-0000-0000-000000000001'),0::bigint);
insert into public.invitations(challenge_id,owner_id,recipient_id,invitation_status,token_hash,token_issued_at,sent_at,responded_at)
select o.challenge_id,c.owner_id,o.challenge_recipient_id,'declined',repeat('b',64),now(),now(),now() from public.challenge_reward_organizers o join public.challenges c on c.id=o.challenge_id where o.challenge_id='a2000000-0000-0000-0000-000000000001';
create temporary table declined_start as select public.start_reward_fulfillment_worker() value;
select test.assert_equals('declined_organizer_is_not_eligible',(select count(*) from public.claim_due_reward_fulfillments((select (value->>'runId')::uuid from declined_start),(select (value->>'leaseToken')::uuid from declined_start),25)),0::bigint);
select public.finish_reward_fulfillment_worker((select (value->>'runId')::uuid from declined_start),(select (value->>'leaseToken')::uuid from declined_start),'succeeded',0,0,0,null);
update public.invitations set invitation_status='accepted' where challenge_id='a2000000-0000-0000-0000-000000000001';
create temporary table fulfillment_start as select public.start_reward_fulfillment_worker() value;
select test.assert_equals('concurrent_worker_cannot_claim_lease',(public.start_reward_fulfillment_worker()->>'status'),'already_running');
create temporary table fulfillment_claim as select * from public.claim_due_reward_fulfillments((select (value->>'runId')::uuid from fulfillment_start),(select (value->>'leaseToken')::uuid from fulfillment_start),25);
select test.assert_equals('one_paid_failed_consequence_creates_one_obligation',(select count(*) from fulfillment_claim),1::bigint);
select test.assert_equals('full_value_is_not_split',(select amount_minor_units||':'||currency from fulfillment_claim),'2500:USD');
select test.assert_equals('stable_internal_idempotency_key',(select idempotency_key from fulfillment_claim),'kinwin-reward:'||(select co.id from public.consequences co where co.challenge_id='a2000000-0000-0000-0000-000000000001'));
select test.assert_equals('recipient_group_is_context_not_allocation',(select recipient_names[1] from fulfillment_claim),'Test recipient');
select public.record_reward_fulfillment_result((select obligation_id from fulfillment_claim),(select (value->>'runId')::uuid from fulfillment_start),(select (value->>'leaseToken')::uuid from fulfillment_start),false,true,null,null,null,'provider_unavailable');
select test.assert_equals('temporary_provider_failure_keeps_payment_truth',(select status from public.consequences where challenge_id='a2000000-0000-0000-0000-000000000001'),'reward_fulfillment_pending');
select test.assert_equals('temporary_provider_failure_keeps_challenge_truth',(select challenge_status from public.challenges where id='a2000000-0000-0000-0000-000000000001'),'completed_failure');
select public.finish_reward_fulfillment_worker((select (value->>'runId')::uuid from fulfillment_start),(select (value->>'leaseToken')::uuid from fulfillment_start),'partial_failure',1,1,1,null);
update private.reward_fulfillments set next_retry_at=clock_timestamp() where id=(select obligation_id from fulfillment_claim);
create temporary table fulfillment_retry_start as select public.start_reward_fulfillment_worker() value;
create temporary table fulfillment_retry_claim as select * from public.claim_due_reward_fulfillments((select (value->>'runId')::uuid from fulfillment_retry_start),(select (value->>'leaseToken')::uuid from fulfillment_retry_start),25);
select test.assert_equals('retry_reuses_the_same_obligation',(select obligation_id from fulfillment_retry_claim),(select obligation_id from fulfillment_claim));
select test.assert_equals('retry_does_not_create_duplicate_provider_obligation',(select count(*) from private.reward_fulfillments f join public.consequences co on co.id=f.consequence_id where co.challenge_id='a2000000-0000-0000-0000-000000000001'),1::bigint);
select public.record_reward_fulfillment_result((select obligation_id from fulfillment_retry_claim),(select (value->>'runId')::uuid from fulfillment_retry_start),(select (value->>'leaseToken')::uuid from fulfillment_retry_start),true,false,'sandbox_order_1','sandbox_reward_1','https://testflight.tremendous.com/rewards/sandbox_reward_1',null);
select test.assert_equals('trusted_provider_evidence_marks_reward_delivered',(select status from public.consequences where challenge_id='a2000000-0000-0000-0000-000000000001'),'reward_delivered');
select test.assert_fails('provider_identity_cannot_change',$stmt$update private.reward_fulfillments set provider_order_id='redirected' where id=(select obligation_id from fulfillment_retry_claim)$stmt$,'23000');
select public.finish_reward_fulfillment_worker((select (value->>'runId')::uuid from fulfillment_retry_start),(select (value->>'leaseToken')::uuid from fulfillment_retry_start),'succeeded',1,1,0,null);
select test.assert_equals('successful_challenge_has_no_fulfillment',(select count(*) from private.reward_fulfillments f join public.consequences co on co.id=f.consequence_id where co.challenge_id='a2000000-0000-0000-0000-000000000002'),0::bigint);
select test.assert_equals('authenticated_cannot_start_fulfillment_worker',has_function_privilege('authenticated','public.start_reward_fulfillment_worker()','execute'),false);
reset role;
set role authenticated;
select test.assert_fails('owner_cannot_read_private_fulfillment','select redemption_url from private.reward_fulfillments','42501');
reset role;
set role anon;
select test.assert_fails('anon_cannot_read_private_fulfillment','select * from private.reward_fulfillments','42501');
reset role;
