import assert from 'node:assert/strict';
import test from 'node:test';
import { buildActiveChallengeViewModel, capBuildCompletions, isValidCutTotal, PreviewConfiguration, PreviewEvent } from './challenge-preview-view-model';
const base = (overrides: Partial<PreviewConfiguration> = {}): PreviewConfiguration => ({ direction: 'build', measurement: 'completion', target: 3, periodUnit: 'week', unit: 'completions', durationWeeks: 6, wholeRequirement: 'Complete at least 16 of 18 planned sessions.', continuity: 'Complete at least 2 sessions every week.', ...overrides });
const view = (configuration: PreviewConfiguration, events: PreviewEvent[] = []) => buildActiveChallengeViewModel({ configuration, events, playbookEntries: [] });
test('Build is truthful at zero, partial, target and capped', () => { assert.match(view(base()).currentPeriod.headline, /^0 of 3/); assert.equal(view(base(), [{ id: '1', order: 1, type: 'build_completion' }]).currentPeriod.status, 'in_progress'); assert.equal(view(base(), [1,2,3].map((order) => ({ id: String(order), order, type: 'build_completion' as const }))).currentPeriod.status, 'met'); assert.equal(capBuildCompletions(5, 3), 3); assert.equal(view(base()).recordedPeriods.kind, 'unavailable'); });
test('Cut back handles absent, within, exact and over totals', () => { const cut = base({ direction: 'cut', measurement: 'time', target: 120, unit: 'minutes', wholeRequirement: 'Stay within the limit.' }); assert.equal(view(cut).currentPeriod.status, 'not_recorded'); assert.match(view(cut, [{ id:'1', order:1, type:'cut_total', value:95 }]).currentPeriod.detail, /25 minutes remain/); assert.equal(view(cut, [{ id:'1', order:1, type:'cut_total', value:120 }]).currentPeriod.status, 'at_limit'); assert.match(view(cut, [{ id:'1', order:1, type:'cut_total', value:130 }]).currentPeriod.detail, /10 minutes over/); assert.equal(isValidCutTotal(-1, 'time'), false); assert.equal(isValidCutTotal(1.5, 'count'), false); });
test('Stop lapse is permanent through recovery view input and never creates financial action', () => { const stop = base({ direction:'stop', measurement:'abstinence', target:0, periodUnit:'challenge', unit:'lapses', wholeRequirement:'No lapses.' }); assert.equal(view(stop, [{ id:'1', order:1, type:'stop_status', status:'intact' }]).currentPeriod.status, 'intact'); const lapsed = buildActiveChallengeViewModel({ configuration:stop, events:[{ id:'1', order:1, type:'stop_status', status:'lapse' }], playbookEntries:[{ id:'p', order:2, source:'recovery', sourceEventType:'stop_status', direction:'stop', obstacle:'stress', strategy:'next_opportunity', recoveryAction:'Resume at the next planned opportunity', note:null, recoveryStatus:'completed', behavior:'No smoking' }] }); assert.equal(lapsed.currentPeriod.status, 'lapse'); assert.equal(lapsed.consequenceState, 'preview_only_no_action'); assert.equal(stop.wholeRequirement, 'No lapses.'); });
test('Shared view exposes unknown history without probabilities', () => { const result = view(base()); assert.equal(result.successPossible.kind, 'unavailable'); assert.equal('probability' in result, false); assert.strictEqual(result, result); });
