import { Href, useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AnimatedPrimaryButton } from '@/components/animated-primary-button';
import { kinwinTheme as theme } from '@/constants/theme';
import { useActiveChallengeView } from '@/hooks/use-active-challenge-view';
import { useReducedMotion } from '@/hooks/use-reduced-motion';
import { playImportantHaptic } from '@/lib/haptics';
const COOL = '#7D8589';
export default function ChallengeHome() { const router = useRouter(); const reduced = useReducedMotion(); const { onboarding, preview, view } = useActiveChallengeView();
  if (!view) return <Shell><Text style={s.eyebrow}>ACTIVE PREVIEW</Text><Text style={s.title}>Complete your challenge draft first.</Text><AnimatedPrimaryButton accessibilityHint="Returns to challenge setup" label="Review setup" onPress={() => router.push('/create/goal' as Href)} reducedMotion={reduced} /></Shell>;
  const activeRecovery = preview.playbookEntries.find((entry) => entry.recoveryStatus === 'active'); const recipients = onboarding.recipients.map((r) => r.name.trim()).filter(Boolean).join(', ');
  const action = () => view.nextAction.type === 'continue_recovery' ? router.push('/challenge/recovery' as Href) : view.nextAction.type === 'review_playbook' || view.nextAction.type === 'recovery_completed' ? router.push('/challenge/playbook' as Href) : router.push('/challenge/check-in' as Href);
  return <Shell><View style={s.notice}><Text style={s.noticeTitle}>PREVIEW · TEMPORARY</Text><Text style={s.noticeText}>Activity in this session disappears on reload.</Text></View>
    <Text style={s.eyebrow}>YOUR REASON</Text><Text style={s.goal}>{onboarding.goal.trim()}</Text><Text style={s.promiseLabel}>YOUR PROMISE</Text><Text style={s.promise}>{onboarding.behaviorText.trim()}</Text><Text style={s.meta}>{onboarding.stakeAmount ? `$${onboarding.stakeAmount.toLocaleString('en-US')} stake` : 'Stake not set'} · {recipients || 'Recipients not set'}</Text>
    <View accessibilityLabel={`Two futures. Current state: ${view.twoFuturesState}`} style={s.futures}><View style={s.threadStem} /><View style={s.fork}><View style={[s.branch, { borderColor: COOL }]}><Text style={[s.branchLabel,{color:COOL}]}>KEEP THE PROMISE</Text><Text style={s.branchCopy}>Your chosen behavior remains the path forward.</Text></View><View style={[s.branch,{borderColor:theme.colors.copper}]}><Text style={s.branchLabel}>LOVED ONES WIN</Text><Text style={s.branchCopy}>The configured consequence applies only after trusted final evaluation.</Text></View></View><Text style={s.state}>{stateLabel(view.twoFuturesState)}</Text></View>
    <Section label="CURRENT PERIOD"><Text style={s.sectionTitle}>{view.currentPeriod.headline}</Text><Text style={s.body}>{view.currentPeriod.detail}</Text>{view.nextAction.type !== 'period_complete' && <AnimatedPrimaryButton accessibilityHint="Opens the next useful challenge action" label={view.nextAction.label} onPress={action} reducedMotion={reduced} />}</Section>
    <Section label="WHOLE CHALLENGE"><Text style={s.sectionTitle}>{view.configuredDuration}</Text><Text style={s.body}>{view.configuredRequirement}</Text><Text style={s.unavailable}>No completed periods have been recorded in this preview.</Text></Section>
    <Section label="NEXT USEFUL ACTION"><Text style={s.sectionTitle}>{view.nextAction.label}</Text><Text style={s.body}>{view.nextAction.detail}</Text>{activeRecovery && <Pressable onPress={() => { void playImportantHaptic(); preview.completeRecovery(activeRecovery.id); }} style={s.textButton} accessibilityRole="button"><Text style={s.textButtonText}>Mark recovery action complete</Text></Pressable>}</Section>
    {view.latestInsight.kind === 'known' && <Section label="FROM YOUR PLAYBOOK"><Text style={s.sectionTitle}>{view.latestInsight.value.recoveryAction}</Text><Text style={s.body}>{view.latestInsight.value.note ?? 'Saved from a meaningful challenge moment.'}</Text><Pressable onPress={() => router.push('/challenge/playbook' as Href)} style={s.textButton}><Text style={s.textButtonText}>Open Playbook</Text></Pressable></Section>}
  </Shell>; }
function stateLabel(state: string) { return ({not_recorded:'No current-period activity recorded yet.',promise_path:'Current preview activity is within the promise.',margin_narrowing:'The current margin is narrowing.',boundary_crossed:'The current period limit has been crossed.',lapse_recorded:'A lapse is recorded. Stop V1 remains zero-lapse.',recovery_active:'Recovery is in progress; the original event remains recorded.'} as Record<string,string>)[state]; }
function Shell({ children }: { children: React.ReactNode }) { return <SafeAreaView style={s.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={s.content}>{children}</ScrollView></SafeAreaView>; }
function Section({label,children}:{label:string;children:React.ReactNode}) { return <View style={s.section}><Text style={s.eyebrow}>{label}</Text>{children}</View>; }
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.ink},content:{width:'100%',maxWidth:600,alignSelf:'center',padding:24,paddingBottom:40,gap:12},notice:{borderBottomWidth:1,borderColor:theme.colors.structureLine,paddingBottom:10},noticeTitle:{color:theme.colors.warmGrey,fontSize:8,fontWeight:'800',letterSpacing:1.2},noticeText:{color:theme.colors.warmGrey,fontSize:11,marginTop:3},eyebrow:{color:theme.colors.copper,fontSize:9,fontWeight:'800',letterSpacing:1.4,marginTop:12},goal:{color:theme.colors.boneMuted,fontFamily:Platform.select({android:'serif',default:'Georgia'}),fontSize:24,lineHeight:30},promiseLabel:{color:COOL,fontSize:9,fontWeight:'800',letterSpacing:1.4,marginTop:8},promise:{color:theme.colors.bone,fontFamily:Platform.select({android:'serif',default:'Georgia'}),fontSize:36,lineHeight:42},meta:{color:theme.colors.warmGrey,fontSize:12},futures:{marginTop:14,paddingVertical:20},threadStem:{alignSelf:'center',width:1,height:28,backgroundColor:theme.colors.copper},fork:{flexDirection:'row',gap:12},branch:{flex:1,minHeight:112,borderTopWidth:2,borderBottomWidth:1,paddingVertical:12},branchLabel:{color:theme.colors.copperBright,fontSize:9,fontWeight:'800',letterSpacing:.8},branchCopy:{color:theme.colors.boneMuted,fontSize:12,lineHeight:18,marginTop:8},state:{color:theme.colors.bone,fontSize:13,lineHeight:19,textAlign:'center',marginTop:14},section:{borderTopWidth:1,borderColor:theme.colors.structureLineStrong,paddingTop:10,gap:10,marginTop:8},sectionTitle:{color:theme.colors.bone,fontFamily:Platform.select({android:'serif',default:'Georgia'}),fontSize:25,lineHeight:31},title:{color:theme.colors.bone,fontSize:34},body:{color:theme.colors.boneMuted,fontSize:14,lineHeight:21},unavailable:{color:theme.colors.warmGrey,fontSize:12,lineHeight:18},textButton:{minHeight:48,justifyContent:'center'},textButtonText:{color:theme.colors.copperBright,fontWeight:'700'}});
