import { Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { kinwinTheme as theme } from '@/constants/theme';
import { useActiveChallengeView } from '@/hooks/use-active-challenge-view';
export default function ProgressScreen(){ const {view}=useActiveChallengeView(); return <SafeAreaView style={s.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>TRUTHFUL PROGRESS</Text><Text style={s.title}>Your challenge position.</Text>{!view?<Text style={s.body}>Complete the challenge draft to view progress.</Text>:<>
<Block label="CURRENT PERIOD"><Text style={s.heading}>{view.currentPeriod.headline}</Text><Text style={s.body}>{view.currentPeriod.detail}</Text></Block>
<Block label="WHOLE CHALLENGE REQUIREMENT"><Text style={s.heading}>{view.configuredDuration}</Text><Text style={s.body}>{view.configuredRequirement}</Text>{view.continuity.kind==='known'&&<Text style={s.secondary}>{view.continuity.value}</Text>}</Block>
<Block label="PERIOD HISTORY"><View style={s.currentNode}><View style={s.node}/><Text style={s.body}>Current preview period · {view.currentPeriod.status.replaceAll('_',' ')}</Text></View><Text style={s.secondary}>Previous periods are not available in this preview. No calendar history has been generated.</Text></Block>
<Block label="TWO FUTURES"><View style={s.future}><Text style={s.futureTitle}>Keep your promise</Text><Text style={s.body}>{keepCopy(view.direction,view.configuredRequirement)}</Text></View><View style={[s.future,s.other]}><Text style={s.futureTitle}>Loved ones win</Text><Text style={s.body}>{otherCopy(view.direction)}</Text></View><Text style={s.secondary}>These are rule conditions, not predictions or probabilities.</Text></Block>
</>}</ScrollView></SafeAreaView> }
function keepCopy(d:string,r:string){return d==='stop'?'Maintain the zero-lapse rule for the complete challenge.':r} function otherCopy(d:string){return d==='stop'?'A confirmed lapse breaks the zero-lapse rule. Recovery still matters and does not erase it.':d==='cut'?'The configured failure condition is reached after trusted period and final evaluation.':'The configured completion requirement is not met after trusted final evaluation.'}
function Block({label,children}:{label:string;children:React.ReactNode}){return <View style={s.block}><Text style={s.eyebrow}>{label}</Text>{children}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.ink},content:{width:'100%',maxWidth:600,alignSelf:'center',padding:24,paddingBottom:40,gap:18},eyebrow:{color:theme.colors.copper,fontSize:9,fontWeight:'800',letterSpacing:1.4},title:{color:theme.colors.bone,fontFamily:Platform.select({android:'serif',default:'Georgia'}),fontSize:38,lineHeight:44},block:{borderTopWidth:1,borderColor:theme.colors.structureLineStrong,paddingTop:16,gap:10},heading:{color:theme.colors.bone,fontFamily:Platform.select({android:'serif',default:'Georgia'}),fontSize:25,lineHeight:31},body:{color:theme.colors.boneMuted,fontSize:14,lineHeight:21},secondary:{color:theme.colors.warmGrey,fontSize:12,lineHeight:18},currentNode:{flexDirection:'row',alignItems:'center',gap:12},node:{width:8,height:8,borderRadius:4,backgroundColor:theme.colors.copperBright},future:{borderTopWidth:2,borderColor:'#7D8589',paddingTop:10},other:{borderColor:theme.colors.copper},futureTitle:{color:theme.colors.bone,fontSize:14,fontWeight:'700'}});
