import { Feather } from '@expo/vector-icons';
import { Href,useFocusEffect,useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useCallback,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { kinwinThemeV2 as theme } from '@/constants/theme-v2';
import { fetchPlaybookEntries,PlaybookCategory,PlaybookEntry } from '@/lib/supabase/playbook-repository';

const LABELS:Record<PlaybookCategory,string>={trigger:'Trigger',obstacle:'Obstacle',replacement:'Replacement',environment:'Environment',support:'Support',lesson:'Lesson'};
type State={kind:'loading'}|{kind:'error';message:string}|{kind:'ready';entries:readonly PlaybookEntry[]};
export default function PlaybookScreen(){const router=useRouter();const [state,setState]=useState<State>({kind:'loading'});
 const load=useCallback(async()=>{setState({kind:'loading'});const result=await fetchPlaybookEntries();setState(result.ok?{kind:'ready',entries:result.value}:{kind:'error',message:result.message});},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={8} onPress={()=>router.back()} style={s.iconButton}><Feather color={theme.colors.ivory} name="chevron-left" size={24}/></Pressable><Text style={s.wordmark}>KINWIN</Text></View><Text style={s.eyebrow}>PERSONAL PLAYBOOK</Text><Text accessibilityRole="header" style={s.title}>What you know about yourself.</Text><Text style={s.intro}>Practical things to remember when you take on your next challenge.</Text><Pressable accessibilityHint="Creates a new Playbook entry" accessibilityRole="button" onPress={()=>router.push('/playbook/edit' as Href)} style={({pressed})=>[s.primary,pressed&&s.primaryPressed]}><Feather color={theme.colors.ivory} name="plus" size={18}/><Text style={s.primaryText}>Add something useful</Text></Pressable>{state.kind==='loading'&&<ActivityIndicator color={theme.colors.rosewood}/>} {state.kind==='error'&&<View style={s.message}><Text style={s.error}>{state.message}</Text><Pressable accessibilityRole="button" hitSlop={8} onPress={()=>void load()}><Text style={s.link}>Try again</Text></Pressable></View>}{state.kind==='ready'&&state.entries.length===0&&<View style={s.empty}><Text style={s.emptyTitle}>Your Playbook is empty.</Text><Text style={s.muted}>Save a trigger, obstacle or strategy that could make next time easier.</Text></View>}{state.kind==='ready'&&state.entries.map(entry=><Pressable key={entry.id} accessibilityHint="Opens this Playbook entry for editing" accessibilityRole="button" onPress={()=>router.push(`/playbook/edit?id=${entry.id}` as Href)} style={({pressed})=>[s.entry,pressed&&s.entryPressed]}><View style={s.entryTop}><Text style={s.category}>{LABELS[entry.category].toUpperCase()}</Text><Feather color={theme.colors.warmGrey} name="edit-2" size={15}/></View><Text style={s.entryText}>{entry.content}</Text></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.ink},content:{width:'100%',maxWidth:560,alignSelf:'center',paddingHorizontal:22,paddingBottom:40,gap:16},header:{height:54,flexDirection:'row',alignItems:'center'},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center',marginLeft:-12},wordmark:{color:theme.colors.ivory,fontSize:12,fontWeight:'800',letterSpacing:4},eyebrow:{color:theme.colors.rosewood,fontSize:10,fontWeight:'800',letterSpacing:1.7},title:{color:theme.colors.ivory,fontFamily:'Georgia',fontSize:31,lineHeight:37},intro:{color:theme.colors.ivoryMuted,fontSize:15,lineHeight:22,maxWidth:430},primary:{minHeight:52,borderRadius:theme.radius.controlled,backgroundColor:theme.colors.rosewood,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},primaryPressed:{opacity:.85},primaryText:{color:theme.colors.ivory,fontSize:15,fontWeight:'800'},message:{gap:10,paddingVertical:20},error:{color:theme.colors.crimsonBright,lineHeight:21},link:{color:theme.colors.rosewood,fontWeight:'800'},empty:{paddingVertical:28,gap:8,borderTopWidth:1,borderTopColor:theme.colors.structureLine},emptyTitle:{color:theme.colors.ivory,fontSize:19,fontWeight:'700'},muted:{color:theme.colors.ivoryMuted,fontSize:14,lineHeight:21},entry:{gap:10,paddingVertical:17,borderTopWidth:1,borderTopColor:theme.colors.structureLine},entryPressed:{opacity:.7},entryTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},category:{color:theme.colors.rosewood,fontSize:9,fontWeight:'900',letterSpacing:1.4},entryText:{color:theme.colors.ivory,fontSize:16,lineHeight:23}});
